### ISSUE TITLE
Misidentifying decimal values as integers

### ISSUE THREAD

**Issue by rollinsio** [sbyrnes/riddl#12]
In a large file that was being converted many percents were mislabeled as integers instead of decimals.

**Comment by sbyrnes** [comment]
Do you have examples of the values in the column?

**Comment by rollinsio** [comment]
Sent out of band, but basically it looks like a lot of values were 0, then would occasionally pop in as decimal values.

**Comment by sbyrnes** [comment]
This was fixed in that columns of all zeroes are classified as Decimal since there is not enough information to decide. 

Also, support for percentages and currencies were improved since they were previous classified as strings if they included symbols.
